l_instrs is :
1000002998
l_cycles is :
7890113054
IPC is :
0.126741276222
The l1 hit rate is 
0.71903293633
==================== Stats when prefetching enabled ===================
l_instrs is :
500121372
l_cycles is :
4584203559
IPC is :
0.10909667635
The l1 hit rate is 
0.721037734806
Traceback (most recent call last):
  File "profile.py", line 107, in <module>
    plt.plot(hit_rate.keys(), hit_rate_p.values(), 'ro', hit_rate.keys(), hit_rate.values(),'bo' )
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3154, in plot
    ret = ax.plot(*args, **kwargs)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1811, in inner
    return func(ax, *args, **kwargs)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1427, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 395, in _grab_next_args
    for seg in self._plot_args(remaining[:isplit], kwargs):
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 364, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 223, in _xy_from_xy
    raise ValueError("x and y must have same first dimension")
ValueError: x and y must have same first dimension
l_instrs is :
1000002988
l_cycles is :
584475727
IPC is :
1.71094014996
The l1 hit rate is 
0.990757266464
Traceback (most recent call last):
  File "profile.py", line 42, in <module>
    instrs_profile[i]=dset[i]['beefy'][0]['instrs'] # / (dset[i]['beefy'][0]['cycles'] +  dset[i]['beefy'][0]['cCycles'])
IndexError: index 59 is out of bounds for axis 0 with size 59
59
l_instrs is :
1000002988
l_cycles is :
584475727
IPC is :
1.71094014996
The l1 hit rate is 
0.990757266464
==================== Stats when prefetching enabled ===================
32
l_instrs is :
499706735
l_cycles is :
317576931
IPC is :
1.57349821798
The l1 hit rate is 
0.991736251701
Traceback (most recent call last):
  File "profile.py", line 86, in <module>
    plt.clf();
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 665, in clf
    gcf().clf()
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 578, in gcf
    return figure()
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 46, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 53, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4agg.py", line 76, in __init__
    FigureCanvasQT.__init__(self, figure)
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt4.py", line 68, in __init__
    _create_qApp()
  File "/home/kartik/anaconda2/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 138, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
